import { readFileSync } from 'node:fs'
import { expect, test } from '@playwright/test'

test('première tournée, ajout patient et export', async ({ page }) => {
  await page.goto('/#/')
  await expect(page.getByRole('heading', { level: 1 })).toBeVisible()
  for (const removed of ['Ma tournée', 'Enregistré sur cet appareil', 'Ouvrir une date', 'Données d’essai', 'Fictif']) await expect(page.getByText(removed)).toHaveCount(0)
  await page.getByRole('link', { name: /Patients/ }).click()
  await page.getByRole('button', { name: 'Ajouter' }).click()
  await page.getByLabel('Nom', { exact: true }).fill('Durand')
  await page.getByLabel('Prénom', { exact: true }).fill('Camille')
  await page.getByLabel('Chambre', { exact: true }).fill('42')
  await page.getByRole('button', { name: 'Enregistrer' }).click()
  await expect(page.getByText('Durand Camille')).toBeVisible()
  await page.getByRole('link', { name: /Journée/ }).click()
  await expect(page.getByText('Durand C.')).toBeVisible()
  await page.getByRole('button', { name: 'A pour Durand Camille' }).click()
  await page.getByRole('link', { name: /Réglages/ }).click()
  await expect(page.locator('pre')).toContainText('Durand')
  const today = await page.evaluate(() => { const d = new Date(); return `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, '0')}-${String(d.getDate()).padStart(2, '0')}` })
  await expect(page.getByLabel('Du', { exact: true })).toHaveValue(today)
  await expect(page.getByLabel('Au', { exact: true })).toHaveValue(today)
  await page.getByRole('button', { name: 'Copier' }).click()
  await expect(page.getByRole('button', { name: 'Copié ✓' })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Copier' })).toBeVisible()
  expect((await page.getByRole('heading', { name: 'Réglages / Export' }).boundingBox())!.width).toBeLessThanOrEqual(1)
  const overflow = await page.evaluate(() => [...document.querySelectorAll('input[type=date]')].some(input => { const box = input.getBoundingClientRect(); const card = input.closest('.card')!.getBoundingClientRect(); return box.right > card.right }))
  expect(overflow).toBe(false)
  await expect(page.getByText(/^v\d+\.\d+\.\d+$/)).toBeVisible()
  await page.getByRole('link', { name: /Journée/ }).click()
  await expect(page.getByText(/^v\d+\.\d+\.\d+$/)).toBeVisible()
  await page.getByRole('link', { name: /Réglages/ }).click()
  await expect(page.getByText('Sur cet appareil')).toHaveCount(0)
  await page.getByRole('link', { name: /Patients/ }).click()
  await page.getByRole('link', { name: /Durand Camille/ }).click()
  await expect(page.getByRole('heading', { name: 'Durand Camille' })).toBeVisible()
  await expect(page.getByLabel('Séances et notes')).toHaveCount(0)
  await page.getByRole('button', { name: 'Séances (1)' }).click()
  await expect(page.getByLabel('Séances et notes')).toContainText('Séance A')
  for (const removed of ['Identité utile', 'Historique', 'trace', 'Gestion de la fiche', 'L’archivage retire']) await expect(page.getByText(removed)).toHaveCount(0)
  await expect(page.getByRole('button', { name: 'Archiver' })).toBeVisible()
})

test('la version de production se recharge hors ligne', async ({ page, context }) => {
  await page.goto('/#/')
  await expect(page.getByRole('heading', { level: 1 })).toBeVisible()
  await page.evaluate(() => navigator.serviceWorker.ready)
  if (!await page.evaluate(() => Boolean(navigator.serviceWorker.controller))) await page.reload()
  await expect.poll(() => page.evaluate(() => Boolean(navigator.serviceWorker.controller))).toBe(true)
  const firstPatient = page.getByRole('button', { name: 'A pour MARTIN Alice' })
  await firstPatient.click()
  await expect(firstPatient).toHaveAttribute('aria-pressed', 'true')
  await context.setOffline(true)
  await page.reload()
  await expect(page.getByRole('heading', { level: 1 })).toBeVisible()
  await expect(page.getByRole('button', { name: 'A pour MARTIN Alice' })).toHaveAttribute('aria-pressed', 'true')
  await page.getByRole('link', { name: /Réglages/ }).click()
  await expect(page.locator('pre')).toContainText('Martin')
})

test('import de patients par copier-coller puis suivi éval/trans', async ({ page }) => {
  // Données fictives au format tableur : en-tête, ligne vide et colonne « groupe » ignorés.
  const pasted = [
    'prenom\tcouverture\tseances\tifd\tpointe\tfacture\teval\ttrans\tfin_ordo\tmedecin\tcotation\tgroupe',
    'EXEMPLE COMPOSE\tBeta\tALD\tLV\tnon\toui\toui\tnon\tnon\t19/05/2027\tDr Test\tRPE 8.5\t1',
    '\t\t\t\t\t\t\t\t\t\t\t',
    'FICTIF\t\tMutuelle\tLJV\tLJ\toui\toui\tnon\tnon\t07/11/2026\t?\tAMC 8,5\t4',
  ].join('\n')
  await page.goto('/#/settings')
  await page.getByLabel('Données patients').fill(pasted)
  page.once('dialog', dialog => void dialog.accept())
  await page.getByRole('button', { name: 'Importer' }).click()
  await expect(page.getByText('2 patients importés.')).toBeVisible()

  await page.getByRole('link', { name: /Journée/ }).click()
  await expect(page.getByText('Martin Alice')).toHaveCount(0)
  await expect(page.getByRole('button', { name: /éval ou trans : date inconnue$/ })).toHaveCount(2)
  await page.getByRole('button', { name: 'A pour EXEMPLE COMPOSE Beta' }).click()
  await page.getByRole('button', { name: 'B pour FICTIF', exact: true }).click()

  await page.getByRole('link', { name: /^EXEMPLE COMPOSE/ }).click()
  await expect(page.getByLabel('Couverture')).toHaveValue('ALD')
  await expect(page.getByLabel('Fin d’ordonnance')).toHaveValue('2027-05-19')
  await expect(page.getByLabel('Médecin traitant')).toHaveValue('Dr Test')
  await expect(page.getByRole('button', { name: 'Séances V' })).toHaveAttribute('aria-pressed', 'true')
  await expect(page.getByRole('button', { name: 'Séances J' })).toHaveAttribute('aria-pressed', 'false')
  await page.getByLabel('Trans').click()
  await expect(page.getByLabel('Trans')).toBeChecked()
  await page.getByRole('link', { name: /Journée/ }).click()
  await expect(page.getByRole('button', { name: /^Note pour EXEMPLE COMPOSE Beta, dernière éval ou trans le/ })).toHaveClass(/recent/)

  await page.getByRole('link', { name: /Réglages/ }).click()
  await expect(page.locator('pre')).toContainText('Exemple Compose fictif')
})

test('journée épurée : appui long pour réordonner, note au triangle, sans zoom', async ({ page }) => {
  await page.goto('/#/?date=2026-09-21')
  await expect(page.getByRole('button', { name: 'Aujourd’hui' })).toHaveCount(0)
  await expect(page.getByRole('button', { name: 'Réorganiser' })).toHaveCount(0)
  await expect(page.locator('.bottom-nav a')).toHaveText(['', '', ''])
  await expect(page.getByRole('link', { name: 'Patients' })).toBeVisible()
  await expect(page.getByText('Repère')).toHaveCount(0)
  await expect(page.getByRole('separator')).toHaveCount(4)
  await expect(page.locator('.separator.off-day')).toHaveCount(1)
  await expect(page.locator('.patient-name strong').filter({ hasText: 'Martin A.' })).toBeVisible()

  const note = page.getByRole('textbox', { name: 'Note du jour pour Martin Alice' })
  await expect(note).toHaveCount(0)
  await page.getByRole('button', { name: /^Note pour Martin Alice/ }).click()
  await expect(note).toBeFocused()
  expect(await note.evaluate(element => getComputedStyle(element).fontSize)).toBe('16px')
  await note.fill('essai')
  await page.getByRole('button', { name: /^Note pour Martin Alice/ }).click()
  await expect(note).toHaveCount(0)

  const rows = page.locator('.tour-list > .sortable-row')
  const last = rows.filter({ hasText: 'Robert P.' })
  const lastBox = (await last.boundingBox())!
  const topBox = (await rows.first().boundingBox())!
  await page.mouse.move(lastBox.x + lastBox.width / 2, lastBox.y + 20)
  await page.mouse.down()
  await page.waitForTimeout(500)
  await page.mouse.move(topBox.x + topBox.width / 2, topBox.y + 4, { steps: 20 })
  await page.mouse.up()
  await expect(rows.first()).toContainText('Robert P.')
  await expect(page).toHaveURL(/#\/\?date=2026-09-21$/)
  await page.reload()
  await expect(page.locator('.tour-list > .sortable-row').first()).toContainText('Robert P.')
})

test('sauvegarde complète puis restauration sur un appareil vierge', async ({ browser, page }) => {
  await page.addInitScript(() => Object.defineProperty(navigator, 'canShare', { value: undefined }))
  await page.goto('/#/?date=2026-09-21')
  await page.getByRole('button', { name: 'B pour Petit Jeanne' }).click()
  await page.getByRole('button', { name: /^Note pour Petit Jeanne/ }).click()
  await page.getByRole('textbox', { name: 'Note du jour pour Petit Jeanne' }).fill('sauvegardée')
  await page.getByRole('link', { name: 'Patients' }).click()
  await page.getByRole('link', { name: /Robert Paul/ }).click()
  await page.getByRole('button', { name: 'Archiver' }).click()
  await page.getByRole('link', { name: /Réglages/ }).click()
  const download = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Sauvegarder' }).click()
  const file = await (await download).path()
  await expect(page.getByText(/^Dernière sauvegarde : /)).toBeVisible()

  const fresh = await (await browser.newContext()).newPage()
  await fresh.goto('/#/settings')
  fresh.once('dialog', dialog => { expect(dialog.message()).toContain('4 patients, 1 journées'); void dialog.accept() })
  await fresh.getByLabel('Fichier de sauvegarde').setInputFiles(file)
  await expect(fresh.getByText('Sauvegarde restaurée.')).toBeVisible()
  await fresh.goto('/#/?date=2026-09-21')
  await expect(fresh.getByRole('button', { name: 'B pour Petit Jeanne' })).toHaveAttribute('aria-pressed', 'true')
  await expect(fresh.getByRole('textbox', { name: 'Note du jour pour Petit Jeanne' })).toHaveValue('sauvegardée')
  await fresh.goto('/#/patients')
  await expect(fresh.getByText('Robert Paul')).toHaveCount(0)
  await fresh.getByLabel('Archivés').check()
  await expect(fresh.getByText('Robert Paul')).toBeVisible()
})

test('bilan du jour ouvert par « + » en plein écran, copié et retrouvé dans la fiche', async ({ page }) => {
  await page.goto('/#/?date=2026-09-22')
  await page.getByRole('link', { name: 'Bilan pour Bernard Louis' }).click()
  await expect(page).toHaveURL(/#\/bilan\/2026-09-22\//)
  const bilan = page.getByRole('textbox', { name: 'Bilan du jour pour Bernard Louis' })
  await expect(page.getByRole('navigation', { name: 'Navigation principale' })).toBeHidden()
  await expect(page.getByRole('button', { name: 'Démarrer la dictée' })).toBeDisabled()
  await expect(page.getByText(/ajoutez une clé OpenRouter/)).toBeVisible()
  // Mode dictée par défaut : le texte ne fait pas apparaître le clavier ; le bouton « Clavier » bascule en saisie.
  await expect(bilan).toHaveAttribute('inputmode', 'none')
  await page.getByRole('button', { name: 'Ouvrir le clavier' }).click()
  await expect(bilan).toHaveAttribute('inputmode', 'text')
  await expect(bilan).toBeFocused()
  await page.getByRole('button', { name: 'Fermer le clavier' }).click()
  await expect(bilan).toHaveAttribute('inputmode', 'none')
  await bilan.fill('Marche 10 m en 12 s.\nDouleur 2/10.')
  await page.getByRole('button', { name: 'Copier' }).click()
  await expect(page.getByRole('button', { name: 'Copié ✓' })).toBeVisible()
  await page.getByRole('link', { name: 'Retour à la journée' }).click()
  await expect(page).toHaveURL(/date=2026-09-22/)
  await expect(page.getByRole('link', { name: 'Bilan pour Bernard Louis' })).toHaveClass(/filled/)
  await page.getByRole('link', { name: /Bernard L\./ }).click()
  await page.getByRole('button', { name: /^Séances \(/ }).click()
  await expect(page.locator('.history-bilan')).toHaveText('Marche 10 m en 12 s.\nDouleur 2/10.')
  await page.getByRole('link', { name: /Réglages/ }).click()
  await page.getByLabel('Du', { exact: true }).fill('2026-09-22')
  await page.getByLabel('Au', { exact: true }).fill('2026-09-22')
  await page.getByRole('button', { name: 'Actualiser' }).click()
  await expect(page.getByText('Rien à exporter sur cette période.')).toBeVisible()
})

// En WebKit, Playwright n’intercepte pas les requêtes d’une page contrôlée par le service worker : il est bloqué ici.
test.describe('dictée', () => {
  test.use({ serviceWorkers: 'block' })
  test('dictée OpenRouter simulée : clé testée, texte inséré au curseur, clé absente de la sauvegarde', async ({ page }) => {
    // Micro et enregistreur factices : le navigateur de test n’a pas de micro ; OpenRouter est simulé.
    await page.addInitScript(() => {
      Object.defineProperty(navigator, 'mediaDevices', { configurable: true, value: { getUserMedia: async () => ({ getTracks: () => [{ stop() {} }] }) } })
      class FakeRecorder {
        static isTypeSupported(type: string) { return type === 'audio/mp4' }
        state = 'inactive'; mimeType = 'audio/mp4'
        ondataavailable: ((event: { data: Blob }) => void) | null = null
        onstop: (() => void) | null = null
        start() { this.state = 'recording' }
        stop() { this.state = 'inactive'; this.ondataavailable?.({ data: new Blob(['son'], { type: 'audio/mp4' }) }); this.onstop?.() }
      }
      Object.defineProperty(window, 'MediaRecorder', { configurable: true, value: FakeRecorder })
    })
    // Réponses simulées avec les en-têtes CORS du vrai service : WebKit les exige, préflight compris.
    const cors = { 'Access-Control-Allow-Origin': '*', 'Access-Control-Allow-Headers': 'Authorization, Content-Type', 'Access-Control-Allow-Methods': 'GET, POST, OPTIONS' }
    const sent: string[] = []
    await page.route('https://openrouter.ai/api/v1/key', route => route.request().method() === 'OPTIONS' ? route.fulfill({ status: 204, headers: cors }) : route.fulfill({ headers: cors, json: { data: { label: 'test' } } }))
    await page.route('https://openrouter.ai/api/v1/audio/transcriptions', route => {
      if (route.request().method() === 'OPTIONS') return route.fulfill({ status: 204, headers: cors })
      sent.push(route.request().headers().authorization ?? '')
      return route.fulfill({ headers: cors, json: { text: sent.length === 1 ? 'Milieu dicté.' : 'Suite dictée.' } })
    })
    await page.goto('/#/settings')
    await page.getByLabel('Clé OpenRouter').fill('sk-or-v1-test1234')
    await page.getByRole('button', { name: 'Enregistrer' }).click()
    await expect(page.getByText('Clé enregistrée sur cet appareil (…1234).')).toBeVisible()
    await expect(page.getByLabel('Modèle')).toHaveValue('openai/whisper-large-v3')
    await page.getByRole('button', { name: 'Tester la clé' }).click()
    await expect(page.locator('.dictation [role=status]')).toHaveText('Clé valide.')
    const [download] = await Promise.all([page.waitForEvent('download'), page.getByRole('button', { name: 'Sauvegarder' }).click()])
    expect(readFileSync((await download.path())!, 'utf8')).not.toContain('sk-or-v1-test1234')

    await page.goto('/#/?date=2026-09-22')
    await page.getByRole('link', { name: 'Bilan pour Martin Alice' }).click()
    const bilan = page.getByRole('textbox', { name: 'Bilan du jour pour Martin Alice' })
    await bilan.fill('Début. Fin.')
    await bilan.press('Home')
    for (let step = 0; step < 6; step++) await bilan.press('ArrowRight')
    await page.getByRole('button', { name: 'Démarrer la dictée' }).click()
    await expect(page.getByText(/Enregistrement 0:0\d \/ 5:00/)).toBeVisible()
    await page.getByRole('button', { name: 'Arrêter la dictée' }).click()
    await expect(bilan).toHaveValue('Début. Milieu dicté. Fin.')
    await page.getByRole('button', { name: 'Démarrer la dictée' }).click()
    await page.getByRole('button', { name: 'Arrêter la dictée' }).click()
    await expect(bilan).toHaveValue('Début. Milieu dicté. Suite dictée. Fin.')
    expect(sent).toEqual(['Bearer sk-or-v1-test1234', 'Bearer sk-or-v1-test1234'])
    await page.getByRole('link', { name: 'Retour à la journée' }).click()
    await page.getByRole('link', { name: 'Bilan pour Martin Alice' }).click()
    await expect(bilan).toHaveValue('Début. Milieu dicté. Suite dictée. Fin.')
  })
})

test('patient pointé puis archivé le jour même : il reste visible et corrigeable, renommé dans l’export', async ({ page }) => {
  await page.goto('/#/')
  await page.getByRole('button', { name: 'A pour Petit Jeanne' }).click()
  await page.getByRole('link', { name: /Petit J\./ }).click()
  const lastName = page.getByLabel('Nom', { exact: true })
  await lastName.fill('Dupont')
  await lastName.blur()
  await expect(page.getByRole('heading', { name: 'Dupont Jeanne' })).toBeVisible()
  await page.getByRole('button', { name: 'Archiver' }).click()
  await page.getByRole('link', { name: /Journée/ }).click()
  await expect(page.getByRole('link', { name: /Dupont J\.\s*Archivé/ })).toBeVisible()
  await expect(page.getByRole('button', { name: 'A pour Dupont Jeanne' })).toHaveAttribute('aria-pressed', 'true')
  await page.getByRole('link', { name: /Réglages/ }).click()
  await expect(page.locator('pre')).toContainText('Dupont')
  await expect(page.locator('pre')).not.toContainText('Petit')
})

test('fiche ouverte depuis la journée : retour à la même date, Éval/Trans en tête, GRP et compteurs', async ({ page }) => {
  await page.goto('/#/?date=2026-09-21')
  await page.getByRole('button', { name: 'A pour Martin Alice' }).click()
  await page.goto('/#/?date=2026-09-24')
  await expect(page.getByText('Dernière séance A il y a 3 jours')).toHaveCount(1)
  await expect(page.locator('.transmission .weeks')).toHaveCount(0)

  await page.getByRole('link', { name: /Martin A\./ }).click()
  await expect(page.getByRole('heading', { name: 'Martin Alice' })).toBeVisible()
  const evalBox = page.getByRole('checkbox', { name: /^Éval/ })
  const headingBox = (await page.getByRole('heading', { name: 'Martin Alice' }).boundingBox())!
  expect((await evalBox.boundingBox())!.y).toBeGreaterThan(headingBox.y)
  expect((await evalBox.boundingBox())!.y).toBeLessThan((await page.getByLabel('Nom', { exact: true }).boundingBox())!.y)
  await expect(page.locator('.follow-up').first()).toContainText('—')
  await evalBox.click()
  await expect(evalBox).toBeChecked()
  await expect(page.locator('.follow-up').first()).toContainText('aujourd’hui')
  await page.getByRole('checkbox', { name: 'GRP' }).click()
  await expect(page.getByRole('checkbox', { name: 'GRP' })).toBeChecked()
  await page.getByRole('link', { name: '← jeudi 24 septembre' }).click()
  await expect(page).toHaveURL(/#\/\?date=2026-09-24$/)

  const row = page.locator('.sortable-row').filter({ hasText: 'Martin A.' })
  await expect(row).toHaveClass(/group/)
  const card = (await row.locator('.patient-row').boundingBox())!
  const stripe = await row.evaluate(element => { const style = getComputedStyle(element, '::before'); return { left: parseFloat(style.left), width: parseFloat(style.width) } })
  expect(stripe.left + stripe.width).toBeLessThanOrEqual(0)
  expect(card.x).toBeGreaterThan(-stripe.left)
  const weeks = row.locator('.transmission .weeks')
  await expect(weeks).toHaveText('0')
  expect((await weeks.boundingBox())!.x).toBeLessThan((await row.locator('.transmission .triangle').boundingBox())!.x)
  await expect(page.locator('.sortable-row').filter({ hasText: 'Bernard L.' })).not.toHaveClass(/group/)

  await page.getByRole('link', { name: 'Patients' }).click()
  await page.getByRole('link', { name: /Bernard Louis/ }).click()
  await expect(page.getByRole('link', { name: '← Patients' })).toBeVisible()
})
