import { readFileSync } from 'node:fs'
import { expect, test, type Page } from '@playwright/test'

// « + » sur la carte propose bilan libre ou Tinetti.
async function openBilan(page: Page, name: string, choice = 'Bilan libre') {
  await page.getByRole('button', { name: `Bilan pour ${name}` }).click()
  await page.getByRole('link', { name: choice }).click()
}

test('première tournée, ajout patient et export', async ({ page }) => {
  await page.goto('/#/')
  await expect(page.getByRole('heading', { level: 1 })).toBeVisible()
  for (const removed of ['Ma tournée', 'Enregistré sur cet appareil', 'Ouvrir une date', 'Données d’essai', 'Fictif']) await expect(page.getByText(removed)).toHaveCount(0)
  await page.getByRole('link', { name: /Patients/ }).click()
  await page.getByRole('button', { name: 'Ajouter' }).click()
  await page.getByLabel('Nom', { exact: true }).fill('Durand')
  await page.getByLabel('Prénom', { exact: true }).fill('Camille')
  await page.getByLabel('Chambre', { exact: true }).fill('42')
  await page.getByRole('button', { name: 'Enregistrer' }).click()
  await expect(page.getByText('Durand Camille')).toBeVisible()
  await page.getByRole('link', { name: /Journée/ }).click()
  await expect(page.getByText('Durand C.')).toBeVisible()
  await page.getByRole('button', { name: 'A pour Durand Camille' }).click()
  await page.getByRole('link', { name: /Réglages/ }).click()
  await expect(page.locator('pre')).toContainText('Durand')
  const today = await page.evaluate(() => { const d = new Date(); return `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, '0')}-${String(d.getDate()).padStart(2, '0')}` })
  await expect(page.getByLabel('Du', { exact: true })).toHaveValue(today)
  await expect(page.getByLabel('Au', { exact: true })).toHaveValue(today)
  await page.getByRole('button', { name: 'Copier' }).click()
  await expect(page.getByRole('button', { name: 'Copié ✓' })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Copier' })).toBeVisible()
  expect((await page.getByRole('heading', { name: 'Réglages / Export' }).boundingBox())!.width).toBeLessThanOrEqual(1)
  const overflow = await page.evaluate(() => [...document.querySelectorAll('input[type=date]')].some(input => { const box = input.getBoundingClientRect(); const card = input.closest('.card')!.getBoundingClientRect(); return box.right > card.right }))
  expect(overflow).toBe(false)
  await expect(page.getByText(/^v\d+\.\d+\.\d+$/)).toBeVisible()
  await page.getByRole('link', { name: /Journée/ }).click()
  await expect(page.getByText(/^v\d+\.\d+\.\d+$/)).toBeVisible()
  await page.getByRole('link', { name: /Réglages/ }).click()
  await expect(page.getByText('Sur cet appareil')).toHaveCount(0)
  await page.getByRole('link', { name: /Patients/ }).click()
  await page.getByRole('link', { name: /Durand Camille/ }).click()
  await expect(page.getByRole('heading', { name: 'Durand Camille' })).toBeVisible()
  await expect(page.getByLabel('Séances et notes')).toHaveCount(0)
  await page.getByRole('button', { name: 'Séances (1)' }).click()
  await expect(page.getByLabel('Séances et notes')).toContainText('Séance A')
  for (const removed of ['Identité utile', 'Historique', 'trace', 'Gestion de la fiche', 'L’archivage retire']) await expect(page.getByText(removed)).toHaveCount(0)
  await expect(page.getByRole('button', { name: 'Archiver' })).toBeVisible()
})

test('la version de production se recharge hors ligne', async ({ page, context }) => {
  await page.goto('/#/')
  await expect(page.getByRole('heading', { level: 1 })).toBeVisible()
  await page.evaluate(() => navigator.serviceWorker.ready)
  if (!await page.evaluate(() => Boolean(navigator.serviceWorker.controller))) await page.reload()
  await expect.poll(() => page.evaluate(() => Boolean(navigator.serviceWorker.controller))).toBe(true)
  const firstPatient = page.getByRole('button', { name: 'A pour MARTIN Alice' })
  await firstPatient.click()
  await expect(firstPatient).toHaveAttribute('aria-pressed', 'true')
  await context.setOffline(true)
  await page.reload()
  await expect(page.getByRole('heading', { level: 1 })).toBeVisible()
  await expect(page.getByRole('button', { name: 'A pour MARTIN Alice' })).toHaveAttribute('aria-pressed', 'true')
  await page.getByRole('link', { name: /Réglages/ }).click()
  await expect(page.locator('pre')).toContainText('Martin')
})

test('import de patients par copier-coller puis suivi éval/trans', async ({ page }) => {
  // Données fictives au format tableur : en-tête, ligne vide et colonne « groupe » ignorés.
  const pasted = [
    'prenom\tcouverture\tseances\tifd\tpointe\tfacture\teval\ttrans\tfin_ordo\tmedecin\tcotation\tgroupe',
    'EXEMPLE COMPOSE\tBeta\tALD\tLV\tnon\toui\toui\tnon\tnon\t19/05/2027\tDr Test\tRPE 8.5\t1',
    '\t\t\t\t\t\t\t\t\t\t\t',
    'FICTIF\t\tMutuelle\tLJV\tLJ\toui\toui\tnon\tnon\t07/11/2026\t?\tAMC 8,5\t4',
  ].join('\n')
  await page.goto('/#/settings')
  await page.getByLabel('Données patients').fill(pasted)
  page.once('dialog', dialog => void dialog.accept())
  await page.getByRole('button', { name: 'Importer' }).click()
  await expect(page.getByText('2 patients importés.')).toBeVisible()

  await page.getByRole('link', { name: /Journée/ }).click()
  await expect(page.getByText('Martin Alice')).toHaveCount(0)
  await expect(page.getByRole('button', { name: /éval ou trans : date inconnue$/ })).toHaveCount(2)
  await page.getByRole('button', { name: 'A pour EXEMPLE COMPOSE Beta' }).click()
  await page.getByRole('button', { name: 'B pour FICTIF', exact: true }).click()

  await page.getByRole('link', { name: /^EXEMPLE COMPOSE/ }).click()
  await expect(page.getByLabel('Couverture')).toHaveValue('ALD')
  await expect(page.getByLabel('Fin d’ordonnance')).toHaveValue('2027-05-19')
  await expect(page.getByLabel('Médecin traitant')).toHaveValue('Dr Test')
  await expect(page.getByRole('button', { name: 'Séances V' })).toHaveAttribute('aria-pressed', 'true')
  await expect(page.getByRole('button', { name: 'Séances J' })).toHaveAttribute('aria-pressed', 'false')
  await page.getByLabel('Trans').click()
  await expect(page.getByLabel('Trans')).toBeChecked()
  await page.getByRole('link', { name: /Journée/ }).click()
  await expect(page.getByRole('button', { name: /^Note pour EXEMPLE COMPOSE Beta, dernière éval ou trans le/ })).toHaveClass(/recent/)

  await page.getByRole('link', { name: /Réglages/ }).click()
  await expect(page.locator('pre')).toContainText('Exemple Compose fictif')
})

test('journée épurée : appui long pour réordonner, note au triangle, sans zoom', async ({ page }) => {
  await page.goto('/#/?date=2026-09-21')
  await expect(page.getByRole('button', { name: 'Aujourd’hui' })).toHaveCount(0)
  await expect(page.getByRole('button', { name: 'Réorganiser' })).toHaveCount(0)
  await expect(page.locator('.bottom-nav a')).toHaveText(['', '', '', ''])
  await expect(page.getByRole('link', { name: 'Patients' })).toBeVisible()
  await expect(page.getByText('Repère')).toHaveCount(0)
  await expect(page.getByRole('separator')).toHaveCount(4)
  await expect(page.locator('.separator.off-day')).toHaveCount(1)
  await expect(page.locator('.patient-name strong').filter({ hasText: 'Martin A.' })).toBeVisible()

  const note = page.getByRole('textbox', { name: 'Note du jour pour Martin Alice' })
  await expect(note).toHaveCount(0)
  await page.getByRole('button', { name: /^Note pour Martin Alice/ }).click()
  await expect(note).toBeFocused()
  expect(await note.evaluate(element => getComputedStyle(element).fontSize)).toBe('16px')
  await note.fill('essai')
  await page.getByRole('button', { name: /^Note pour Martin Alice/ }).click()
  await expect(note).toHaveCount(0)

  const rows = page.locator('.tour-list > .sortable-row')
  const last = rows.filter({ hasText: 'Robert P.' })
  const lastBox = (await last.boundingBox())!
  const topBox = (await rows.first().boundingBox())!
  await page.mouse.move(lastBox.x + lastBox.width / 2, lastBox.y + 20)
  await page.mouse.down()
  await page.waitForTimeout(500)
  await page.mouse.move(topBox.x + topBox.width / 2, topBox.y + 4, { steps: 20 })
  await page.mouse.up()
  await expect(rows.first()).toContainText('Robert P.')
  await expect(page).toHaveURL(/#\/\?date=2026-09-21$/)
  await page.reload()
  await expect(page.locator('.tour-list > .sortable-row').first()).toContainText('Robert P.')
})

test('sauvegarde complète puis restauration sur un appareil vierge', async ({ browser, page }) => {
  await page.addInitScript(() => Object.defineProperty(navigator, 'canShare', { value: undefined }))
  await page.goto('/#/?date=2026-09-21')
  await page.getByRole('button', { name: 'B pour Petit Jeanne' }).click()
  await page.getByRole('button', { name: /^Note pour Petit Jeanne/ }).click()
  await page.getByRole('textbox', { name: 'Note du jour pour Petit Jeanne' }).fill('sauvegardée')
  await page.getByRole('link', { name: 'Patients' }).click()
  await page.getByRole('link', { name: /Robert Paul/ }).click()
  await page.getByRole('button', { name: 'Archiver' }).click()
  await page.getByRole('link', { name: /Réglages/ }).click()
  const download = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Sauvegarder' }).click()
  const file = await (await download).path()
  await expect(page.getByText(/^Dernière sauvegarde : /)).toBeVisible()

  const fresh = await (await browser.newContext()).newPage()
  await fresh.goto('/#/settings')
  fresh.once('dialog', dialog => { expect(dialog.message()).toContain('4 patients, 1 journées'); void dialog.accept() })
  await fresh.getByLabel('Fichier de sauvegarde').setInputFiles(file)
  await expect(fresh.getByText('Sauvegarde restaurée.')).toBeVisible()
  await fresh.goto('/#/?date=2026-09-21')
  await expect(fresh.getByRole('button', { name: 'B pour Petit Jeanne' })).toHaveAttribute('aria-pressed', 'true')
  await expect(fresh.getByRole('textbox', { name: 'Note du jour pour Petit Jeanne' })).toHaveValue('sauvegardée')
  await fresh.goto('/#/patients')
  await expect(fresh.getByText('Robert Paul')).toHaveCount(0)
  await fresh.getByLabel('Archivés').check()
  await expect(fresh.getByText('Robert Paul')).toBeVisible()
})

test('bilan du jour ouvert par « + » en plein écran, copié et retrouvé dans la fiche', async ({ page }) => {
  await page.goto('/#/?date=2026-09-22')
  await openBilan(page, 'Bernard Louis')
  await expect(page).toHaveURL(/#\/bilan\/2026-09-22\//)
  const bilan = page.getByRole('textbox', { name: 'Bilan du jour pour Bernard Louis' })
  await expect(page.getByRole('navigation', { name: 'Navigation principale' })).toBeHidden()
  await expect(page.getByRole('button', { name: 'Démarrer la dictée' })).toBeDisabled()
  await expect(page.getByText(/ajoutez une clé OpenRouter/)).toBeVisible()
  // Mode dictée par défaut : le texte ne fait pas apparaître le clavier ; le bouton « Clavier » bascule en saisie.
  await expect(bilan).toHaveAttribute('inputmode', 'none')
  await page.getByRole('button', { name: 'Ouvrir le clavier' }).click()
  await expect(bilan).toHaveAttribute('inputmode', 'text')
  await expect(bilan).toBeFocused()
  await page.getByRole('button', { name: 'Fermer le clavier' }).click()
  await expect(bilan).toHaveAttribute('inputmode', 'none')
  await bilan.fill('Marche 10 m en 12 s.')
  await page.getByRole('button', { name: 'Aller à la ligne' }).click()
  await bilan.pressSequentially('Douleur 2/10.')
  await expect.poll(() => bilan.innerHTML()).toBe('Marche 10 m en 12 s.<br>Douleur 2/10.')
  await page.getByRole('button', { name: 'Copier' }).click()
  await expect(page.getByRole('button', { name: 'Copié' })).toBeVisible()
  await page.getByRole('link', { name: 'Retour à la journée' }).click()
  await expect(page).toHaveURL(/date=2026-09-22/)
  await expect(page.getByRole('button', { name: 'Bilan pour Bernard Louis' })).toHaveClass(/filled/)
  await page.getByRole('link', { name: /Bernard L\./ }).click()
  await page.getByRole('button', { name: /^Séances \(/ }).click()
  await expect.poll(() => page.locator('.history-bilan').innerHTML()).toBe('Marche 10 m en 12 s.<br>Douleur 2/10.')
  await page.getByRole('link', { name: /Réglages/ }).click()
  await page.getByLabel('Du', { exact: true }).fill('2026-09-22')
  await page.getByLabel('Au', { exact: true }).fill('2026-09-22')
  await page.getByRole('button', { name: 'Actualiser' }).click()
  await expect(page.getByText('Rien à exporter sur cette période.')).toBeVisible()
})

test('onglet Bilans : ordre de saisie, copie qui coche la transmission, suppression, passage à la ligne', async ({ page, context }) => {
  await context.grantPermissions(['clipboard-read', 'clipboard-write']).catch(() => {})
  await page.goto('/#/?date=2026-09-22')
  await openBilan(page, 'Petit Jeanne')
  const petit = page.getByRole('textbox', { name: 'Bilan du jour pour Petit Jeanne' })
  await petit.fill('Marche.Douleur 2/10.')
  await petit.press('End')
  for (let step = 0; step < 13; step++) await petit.press('ArrowLeft')
  await page.getByRole('button', { name: 'Aller à la ligne' }).click()
  await expect.poll(() => petit.innerHTML()).toBe('Marche.<br>Douleur 2/10.')
  // Mise en forme après coup : sélectionner « Marche » puis Gras.
  await petit.evaluate((element: HTMLElement) => { const range = document.createRange(); range.setStart(element.firstChild!, 0); range.setEnd(element.firstChild!, 6); const selection = window.getSelection()!; selection.removeAllRanges(); selection.addRange(range) })
  await page.getByRole('button', { name: 'Gras' }).click()
  await expect(petit.locator('b')).toHaveText('Marche')
  await expect(page.getByRole('button', { name: 'Gras' })).toHaveAttribute('aria-pressed', 'true')
  await page.getByRole('link', { name: 'Retour à la journée' }).click()
  await openBilan(page, 'Bernard Louis')
  await page.getByRole('textbox', { name: 'Bilan du jour pour Bernard Louis' }).fill('Transferts autonomes.')
  await expect(page.getByRole('button', { name: 'Copier' })).toBeEnabled()
  await page.getByRole('link', { name: 'Retour à la journée' }).click()

  await page.getByRole('link', { name: 'Bilans' }).click()
  await page.getByLabel('Date').fill('2026-09-22')
  await expect(page.getByRole('heading', { name: '0 / 2 bilans copiés' })).toBeVisible()
  await expect(page.locator('.bilan-summary strong')).toHaveText(['Petit J.', 'Bernard L.'])
  await expect(page.getByText('Transferts autonomes.')).toHaveCount(0)
  await page.getByRole('button', { name: /Bernard L\./ }).click()
  await expect(page.getByText('Transferts autonomes.')).toBeVisible()
  page.once('dialog', dialog => void dialog.dismiss())
  await page.getByRole('button', { name: 'Supprimer le bilan de Bernard Louis' }).click()
  await expect(page.getByText('Transferts autonomes.')).toBeVisible()
  // Copie enrichie : le presse-papiers reçoit le HTML (gras compris) et le texte brut.
  await page.evaluate(() => {
    const store = window as unknown as { copied?: { html: string; text: string } }
    Clipboard.prototype.write = async function (items: ClipboardItem[]) { store.copied = { html: await (await items[0].getType('text/html')).text(), text: await (await items[0].getType('text/plain')).text() } }
  })
  await page.getByRole('button', { name: 'Copier le bilan de Petit Jeanne' }).click()
  await expect.poll(() => page.evaluate(() => (window as unknown as { copied?: unknown }).copied)).toEqual({ html: '<b>Marche</b>.<br>Douleur 2/10.', text: 'Marche.\nDouleur 2/10.' })
  await page.getByRole('button', { name: /Petit J\./ }).click()
  await expect(page.locator('.bilan-body b')).toHaveText('Marche')
  await page.getByRole('button', { name: 'Copier le bilan de Bernard Louis' }).click()
  await expect(page.getByRole('heading', { name: '2 / 2 bilans copiés' })).toBeVisible()
  await expect(page.getByLabel('copié')).toHaveCount(2)
  await page.locator('.bilan-list li', { hasText: 'Bernard L.' }).getByRole('link', { name: 'Modifier' }).click()
  await expect(page.getByRole('textbox', { name: 'Bilan du jour pour Bernard Louis' })).toHaveText('Transferts autonomes.')
  await page.getByRole('link', { name: 'Retour aux bilans' }).click()
  await expect(page.getByRole('heading', { name: '2 / 2 bilans copiés' })).toBeVisible()

  await page.getByRole('link', { name: 'Patients' }).click()
  await page.getByRole('link', { name: /Bernard Louis/ }).click()
  await expect(page.getByLabel('Trans')).toBeChecked()
  await page.getByRole('button', { name: /^Séances \(/ }).click()
  page.once('dialog', dialog => void dialog.accept())
  await page.getByRole('button', { name: 'Supprimer le bilan de Bernard Louis' }).click()
  await expect(page.locator('.history-bilan')).toHaveCount(0)
  await page.getByRole('link', { name: 'Bilans' }).click()
  await page.getByLabel('Date').fill('2026-09-22')
  await expect(page.getByRole('heading', { name: '1 / 1 bilans copiés' })).toBeVisible()
})

test('bilan annulé par la croix : il revient à son état d’ouverture', async ({ page }) => {
  await page.goto('/#/?date=2026-09-22')
  await openBilan(page, 'Robert Paul')
  await page.getByRole('textbox', { name: 'Bilan du jour pour Robert Paul' }).fill('Saisi sur le mauvais patient')
  await page.getByRole('button', { name: 'Annuler et quitter' }).click()
  await expect(page).toHaveURL(/date=2026-09-22/)
  await expect(page.getByRole('button', { name: 'Bilan pour Robert Paul' })).not.toHaveClass(/filled/)
  await openBilan(page, 'Robert Paul')
  await expect(page.getByRole('textbox', { name: 'Bilan du jour pour Robert Paul' })).toHaveText('')
})

test('Tinetti : cotation, volets, dictée, copie qui coche Éval, consultation et annulation', async ({ page }) => {
  await page.goto('/#/?date=2026-09-22')
  await openBilan(page, 'Petit Jeanne', 'Test de Tinetti')
  await expect(page.getByRole('tab', { name: 'Grille' })).toHaveAttribute('aria-selected', 'true')
  await expect(page.getByRole('heading', { name: 'Équilibre 0/16' })).toBeVisible()
  await page.getByRole('radiogroup', { name: '1. Équilibre en position assise' }).getByRole('radio', { name: /^1 – / }).click()
  await page.getByRole('radiogroup', { name: '2. Se mettre debout' }).getByRole('radio', { name: /^2 – / }).click()
  await page.getByRole('radiogroup', { name: '8. Rotation de 360° – Stabilité' }).getByRole('radio', { name: /^1 – / }).click()
  await expect(page.getByRole('heading', { name: 'Équilibre 4/16' })).toBeVisible()
  await page.getByRole('radiogroup', { name: '2. Se mettre debout' }).getByRole('radio', { name: /^2 – / }).click()
  await expect(page.getByRole('heading', { name: 'Équilibre 2/16' })).toBeVisible()
  // Équilibre puis marche se suivent dans le même volet.
  await page.getByRole('radiogroup', { name: '14. Marche déviante' }).getByRole('radio', { name: /^2 – / }).click()
  await expect(page.getByRole('heading', { name: 'Marche 2/12' })).toBeVisible()
  await expect(page.getByLabel('Total 4 sur 28')).toBeVisible()
  await page.getByRole('tab', { name: 'Dictée' }).click()
  await expect(page.getByRole('tab', { name: 'Dictée' })).toHaveAttribute('aria-selected', 'true')
  const notes = page.getByRole('textbox', { name: 'Observations Tinetti pour Petit Jeanne' })
  await expect(notes).toHaveAttribute('inputmode', 'none')
  await page.getByRole('button', { name: 'Ouvrir le clavier' }).click()
  await expect(notes).toHaveAttribute('inputmode', 'text')
  await expect(page.getByRole('button', { name: 'Démarrer la dictée' })).toHaveCount(0)
  await page.getByRole('button', { name: 'Fermer le clavier' }).click()
  await notes.fill('Marche prudente.')
  await notes.evaluate((element: HTMLElement) => { const range = document.createRange(); range.setStart(element.firstChild!, 0); range.setEnd(element.firstChild!, 6); const selection = window.getSelection()!; selection.removeAllRanges(); selection.addRange(range) })
  await page.getByRole('button', { name: 'Gras' }).click()
  await page.evaluate(() => {
    const store = window as unknown as { copied?: { html: string; text: string } }
    Clipboard.prototype.write = async function (items: ClipboardItem[]) { store.copied = { html: await (await items[0].getType('text/html')).text(), text: await (await items[0].getType('text/plain')).text() } }
  })
  await page.getByRole('button', { name: 'Copier' }).click()
  await expect.poll(() => page.evaluate(() => (window as unknown as { copied?: { html: string } }).copied?.html)).toBe('<u><b>Tinetti</b></u> : <b>4/28</b> (équilibre 2/16, marche 2/12) – cotation incomplète<br>Items non cotés : 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 15, 16.<br><b>Marche</b> prudente.')
  await page.getByRole('link', { name: 'Retour à la journée' }).click()
  await expect(page.getByRole('button', { name: 'Bilan pour Petit Jeanne' })).toHaveClass(/filled/)

  await page.getByRole('link', { name: 'Bilans' }).click()
  await page.getByLabel('Date').fill('2026-09-22')
  await expect(page.getByText('Tinetti 4/28')).toBeVisible()
  await expect(page.getByRole('heading', { name: '1 / 1 bilans copiés' })).toBeVisible()
  await page.getByRole('link', { name: 'Patients' }).click()
  await page.getByRole('link', { name: /Petit Jeanne/ }).click()
  await expect(page.getByLabel('Éval')).toBeChecked()
  await expect(page.getByLabel('Trans')).not.toBeChecked()
  await page.getByRole('button', { name: /^Séances \(/ }).click()
  await expect(page.locator('.history-bilan')).toContainText('4/28')

  // Un nouveau Tinetti annulé par la croix ne laisse rien.
  await page.goto('/#/?date=2026-09-22')
  await openBilan(page, 'Robert Paul', 'Test de Tinetti')
  await page.getByRole('radiogroup', { name: '7. Yeux fermés (pieds joints)' }).getByRole('radio', { name: /^1 – / }).click()
  await page.getByRole('button', { name: 'Annuler et quitter' }).click()
  await expect(page.getByRole('button', { name: 'Bilan pour Robert Paul' })).not.toHaveClass(/filled/)
})

// En WebKit, Playwright n’intercepte pas les requêtes d’une page contrôlée par le service worker : il est bloqué ici.
test.describe('dictée', () => {
  test.use({ serviceWorkers: 'block' })
  test('dictée OpenRouter simulée : clé testée, texte inséré au curseur, clé absente de la sauvegarde', async ({ page }) => {
    // Micro et enregistreur factices : le navigateur de test n’a pas de micro ; OpenRouter est simulé.
    // Sans partage natif (WebKit macOS l’expose) : « Sauvegarder » télécharge le fichier.
    await page.addInitScript(() => Object.defineProperty(navigator, 'canShare', { value: undefined }))
    await page.addInitScript(() => {
      Object.defineProperty(navigator, 'mediaDevices', { configurable: true, value: { getUserMedia: async () => ({ getTracks: () => [{ stop() {} }] }) } })
      class FakeRecorder {
        static isTypeSupported(type: string) { return type === 'audio/mp4' }
        state = 'inactive'; mimeType = 'audio/mp4'
        ondataavailable: ((event: { data: Blob }) => void) | null = null
        onstop: (() => void) | null = null
        start() { this.state = 'recording' }
        stop() { this.state = 'inactive'; this.ondataavailable?.({ data: new Blob(['son'], { type: 'audio/mp4' }) }); this.onstop?.() }
      }
      Object.defineProperty(window, 'MediaRecorder', { configurable: true, value: FakeRecorder })
    })
    // Réponses simulées avec les en-têtes CORS du vrai service : WebKit les exige, préflight compris.
    const cors = { 'Access-Control-Allow-Origin': '*', 'Access-Control-Allow-Headers': 'Authorization, Content-Type', 'Access-Control-Allow-Methods': 'GET, POST, OPTIONS' }
    const sent: string[] = []
    await page.route('https://openrouter.ai/api/v1/key', route => route.request().method() === 'OPTIONS' ? route.fulfill({ status: 204, headers: cors }) : route.fulfill({ headers: cors, json: { data: { label: 'test' } } }))
    await page.route('https://openrouter.ai/api/v1/audio/transcriptions', route => {
      if (route.request().method() === 'OPTIONS') return route.fulfill({ status: 204, headers: cors })
      sent.push(route.request().headers().authorization ?? '')
      return route.fulfill({ headers: cors, json: { text: sent.length === 1 ? 'Milieu dicté.' : 'Suite dictée.' } })
    })
    await page.goto('/#/settings')
    await page.getByLabel('Clé OpenRouter').fill('sk-or-v1-test1234')
    await page.getByRole('button', { name: 'Enregistrer' }).click()
    await expect(page.getByText('Clé enregistrée sur cet appareil (…1234).')).toBeVisible()
    await expect(page.getByLabel('Modèle de transcription')).toHaveValue('openai/whisper-large-v3')
    await page.getByRole('button', { name: 'Tester la clé' }).click()
    await expect(page.locator('.dictation [role=status]')).toHaveText('Clé valide.')
    const [download] = await Promise.all([page.waitForEvent('download'), page.getByRole('button', { name: 'Sauvegarder' }).click()])
    expect(readFileSync((await download.path())!, 'utf8')).not.toContain('sk-or-v1-test1234')

    await page.goto('/#/?date=2026-09-22')
    await openBilan(page, 'Martin Alice')
    const bilan = page.getByRole('textbox', { name: 'Bilan du jour pour Martin Alice' })
    await bilan.fill('Début. Fin.')
    // Curseur au début posé par script : « Home » ne le fait pas sous macOS.
    await bilan.evaluate(element => { const range = document.createRange(); range.setStart(element.firstChild!, 0); range.collapse(true); getSelection()!.removeAllRanges(); getSelection()!.addRange(range) })
    for (let step = 0; step < 6; step++) await bilan.press('ArrowRight')
    await page.getByRole('button', { name: 'Démarrer la dictée' }).click()
    await expect(page.getByText(/Enregistrement 0:0\d \/ 5:00/)).toBeVisible()
    await page.getByRole('button', { name: 'Arrêter la dictée' }).click()
    await expect(bilan).toHaveText('Début. Milieu dicté. Fin.')
    await page.getByRole('button', { name: 'Démarrer la dictée' }).click()
    await page.getByRole('button', { name: 'Arrêter la dictée' }).click()
    await expect(bilan).toHaveText('Début. Milieu dicté. Suite dictée. Fin.')
    expect(sent).toEqual(['Bearer sk-or-v1-test1234', 'Bearer sk-or-v1-test1234'])
    await page.getByRole('link', { name: 'Retour à la journée' }).click()
    await openBilan(page, 'Martin Alice')
    await expect(bilan).toHaveText('Début. Milieu dicté. Suite dictée. Fin.')
  })

  test('assistant IA simulé : synthèse Tinetti anonymisée, relecture, validation ; correction du bilan libre', async ({ page }) => {
    const cors = { 'Access-Control-Allow-Origin': '*', 'Access-Control-Allow-Headers': 'Authorization, Content-Type', 'Access-Control-Allow-Methods': 'GET, POST, OPTIONS' }
    const bodies: { model: string; messages: { role: string; content: string }[]; response_format?: unknown }[] = []
    await page.route('https://openrouter.ai/api/v1/chat/completions', route => {
      if (route.request().method() === 'OPTIONS') return route.fulfill({ status: 204, headers: cors })
      const body = route.request().postDataJSON()
      bodies.push(body)
      const content = body.response_format
        ? JSON.stringify({ cotations: { e2: 2, e3: 1, m16: 1 }, observations: 'Marche <b>prudente</b> avec [patient].\nTransferts lents.', a_verifier: [{ ligne: 'e2', raison: 'dictée : se lève sans les bras' }, { ligne: 'm16', raison: 'talons proches ?' }, { ligne: 'm15', raison: 'non coté' }] })
        : 'Bonjour [patient], la patiente marche lentement.'
      return route.fulfill({ headers: cors, json: { choices: [{ message: { content } }] } })
    })
    await page.goto('/#/settings')
    await page.getByLabel('Clé OpenRouter').fill('sk-or-v1-test5678')
    await page.getByRole('button', { name: 'Enregistrer' }).click()
    const model = page.getByLabel('Modèle d’analyse')
    await model.fill('deepseek/modele-test')
    await model.blur()
    await page.getByRole('button', { name: 'Tester le modèle' }).click()
    await expect(page.getByText(/^Modèle joignable \(réponse en/)).toBeVisible()
    await page.getByText('Prompt : Synthèse du test de Tinetti').click()
    const prompt = page.getByLabel('Prompt Synthèse du test de Tinetti')
    await expect(prompt).toHaveValue(/Règles propres au test de Tinetti/)
    await prompt.fill('Prompt personnalisé de test.')
    await prompt.blur()
    await expect(page.getByText('Prompt : Synthèse du test de Tinetti (modifié)')).toBeVisible()

    // Sexe renseigné dans la fiche, utilisé pour les accords.
    await page.getByRole('link', { name: 'Patients' }).click()
    await page.getByRole('link', { name: /Petit Jeanne/ }).click()
    await page.getByRole('button', { name: 'Sexe F' }).click()
    await expect(page.getByRole('button', { name: 'Sexe F' })).toHaveAttribute('aria-pressed', 'true')

    await page.goto('/#/?date=2026-09-22')
    await openBilan(page, 'Petit Jeanne', 'Test de Tinetti')
    await page.getByRole('radiogroup', { name: '1. Équilibre en position assise' }).getByRole('radio', { name: /^1 – / }).click()
    await page.getByRole('radiogroup', { name: '2. Se mettre debout' }).getByRole('radio', { name: /^1 – / }).click()
    await page.getByRole('tab', { name: 'Dictée' }).click()
    await page.getByRole('textbox', { name: 'Observations Tinetti pour Petit Jeanne' }).fill('Madame Petit marche prudemment, Jeanne se lève sans les bras.')
    await page.getByRole('button', { name: '✨ Lancer' }).click()
    // Écran 1, ouvert tout seul : la grille est déjà remplie (✨ cotées par l’IA, ⚠ conflit ou doute), sans rien valider ligne à ligne.
    const review = page.getByRole('dialog', { name: 'Synthèse du test' })
    await expect(review.locator('li', { hasText: 'possible > 1 tentative' })).toContainText('✨')
    await expect(review.locator('li', { hasText: 'possible > 1 tentative' })).not.toContainText('IA')
    await expect(review.locator('li.doubt')).toHaveCount(2)
    await expect(review.getByText('Non cotés : 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15.', { exact: true })).toBeVisible()
    await expect(review.getByText('Données envoyées à l’IA')).toBeVisible()
    const request = bodies.at(-1)!
    expect(request.model).toBe('deepseek/modele-test')
    expect(request.messages[0].content).toBe('Prompt personnalisé de test.')
    expect(request.messages[1].content).not.toMatch(/Petit|Jeanne/)
    expect(JSON.parse(request.messages[1].content)).toMatchObject({ patient: 'patiente', dictee: 'Madame [patient] marche prudemment, [patient] se lève sans les bras.' })
    await review.getByRole('button', { name: 'Retour à la grille' }).click()
    await page.getByRole('tab', { name: 'Grille' }).click()
    await expect(page.getByRole('heading', { name: 'Équilibre 3/16' })).toBeVisible()
    const tries = page.getByRole('radiogroup', { name: '3. Tentatives pour se mettre debout' })
    await expect(tries.getByRole('radio', { name: /^1 – / })).toHaveAttribute('aria-checked', 'true')
    await expect(tries.getByRole('radio', { name: /^1 – / })).toContainText('✨')
    await expect(page.getByRole('radiogroup', { name: '2. Se mettre debout' }).getByRole('note')).toHaveText('⚠ dictée : se lève sans les bras')
    await expect(page.getByText(/^✓ Synthèse faite en [0-9,]+ s · 2 ⚠$/)).toBeVisible()
    // « Voir » rouvre l’écran 1 sans nouvel appel ; « Valider » passe à la transmission en plein écran.
    const calls = bodies.length
    await page.getByRole('button', { name: 'Voir' }).click()
    await review.getByRole('button', { name: 'Valider' }).click()
    expect(bodies.length).toBe(calls)
    const transmission = page.getByRole('textbox', { name: 'Transmission Tinetti pour Petit Jeanne' })
    await expect.poll(() => transmission.innerHTML()).toContain('<b>4/28</b>')
    await expect(transmission).toContainText('Marche prudente avec [patient].')
    await expect(transmission).toHaveAttribute('inputmode', 'none')
    await page.getByRole('button', { name: 'Aller à la ligne' }).click()
    await transmission.press('End')
    await transmission.pressSequentially('Revoir dans 3 mois.')
    await page.getByRole('button', { name: 'Valider' }).click()
    await expect(page).toHaveURL(/#\/\?date=2026-09-22/)
    // Relancer après une transmission validée demande l’autorisation de la remplacer.
    await openBilan(page, 'Petit Jeanne', 'Test de Tinetti')
    page.once('dialog', dialog => { expect(dialog.message()).toContain('Remplacer le texte de transmission'); void dialog.dismiss() })
    await page.getByRole('button', { name: '✨ Relancer' }).click()
    expect(bodies.length).toBe(calls)
    await page.getByRole('link', { name: 'Retour à la journée' }).click()
    await page.getByRole('link', { name: 'Bilans' }).click()
    await page.getByLabel('Date').fill('2026-09-22')
    await page.getByRole('button', { name: /Petit J\./ }).click()
    await expect(page.locator('.bilan-body b', { hasText: 'prudente' })).toBeVisible()
    await expect(page.locator('.bilan-body')).toContainText('Revoir dans 3 mois.')

    // Correction du bilan libre : une seule passe, nom remis à sa place, correction annulable.
    await page.goto('/#/?date=2026-09-22')
    await openBilan(page, 'Petit Jeanne')
    const bilan = page.getByRole('textbox', { name: 'Bilan du jour pour Petit Jeanne' })
    await bilan.fill('bonjour Jeanne, la patiente marche lentment.')
    await page.getByRole('button', { name: '✨ Corriger' }).click()
    await expect(bilan).toHaveText('Bonjour Jeanne, la patiente marche lentement.')
    const correction = bodies.at(-1)!
    expect(correction.response_format).toBeUndefined()
    expect(correction.messages[1].content).toBe('Sexe : patiente\n\nTexte :\nbonjour [patient], la patiente marche lentment.')
    await page.getByRole('button', { name: 'Annuler la correction' }).click()
    await expect(bilan).toHaveText('bonjour Jeanne, la patiente marche lentment.')
  })
})

test('patient pointé puis archivé le jour même : il reste visible et corrigeable, renommé dans l’export', async ({ page }) => {
  await page.goto('/#/')
  await page.getByRole('button', { name: 'A pour Petit Jeanne' }).click()
  await page.getByRole('link', { name: /Petit J\./ }).click()
  const lastName = page.getByLabel('Nom', { exact: true })
  await lastName.fill('Dupont')
  await lastName.blur()
  await expect(page.getByRole('heading', { name: 'Dupont Jeanne' })).toBeVisible()
  await page.getByRole('button', { name: 'Archiver' }).click()
  await page.getByRole('link', { name: /Journée/ }).click()
  await expect(page.getByRole('link', { name: /Dupont J\.\s*Archivé/ })).toBeVisible()
  await expect(page.getByRole('button', { name: 'A pour Dupont Jeanne' })).toHaveAttribute('aria-pressed', 'true')
  await page.getByRole('link', { name: /Réglages/ }).click()
  await expect(page.locator('pre')).toContainText('Dupont')
  await expect(page.locator('pre')).not.toContainText('Petit')
})

test('fiche ouverte depuis la journée : retour à la même date, Éval/Trans en tête, GRP et compteurs', async ({ page }) => {
  await page.goto('/#/?date=2026-09-21')
  await page.getByRole('button', { name: 'A pour Martin Alice' }).click()
  await page.goto('/#/?date=2026-09-24')
  await expect(page.getByText('Dernière séance A il y a 3 jours')).toHaveCount(1)
  await expect(page.locator('.transmission .weeks')).toHaveCount(0)

  await page.getByRole('link', { name: /Martin A\./ }).click()
  await expect(page.getByRole('heading', { name: 'Martin Alice' })).toBeVisible()
  const evalBox = page.getByRole('checkbox', { name: /^Éval/ })
  const headingBox = (await page.getByRole('heading', { name: 'Martin Alice' }).boundingBox())!
  expect((await evalBox.boundingBox())!.y).toBeGreaterThan(headingBox.y)
  expect((await evalBox.boundingBox())!.y).toBeLessThan((await page.getByLabel('Nom', { exact: true }).boundingBox())!.y)
  await expect(page.locator('.follow-up').first()).toContainText('—')
  await evalBox.click()
  await expect(evalBox).toBeChecked()
  await expect(page.locator('.follow-up').first()).toContainText('aujourd’hui')
  await page.getByRole('checkbox', { name: 'GRP' }).click()
  await expect(page.getByRole('checkbox', { name: 'GRP' })).toBeChecked()
  await page.getByRole('link', { name: '← jeudi 24 septembre' }).click()
  await expect(page).toHaveURL(/#\/\?date=2026-09-24$/)

  const row = page.locator('.sortable-row').filter({ hasText: 'Martin A.' })
  await expect(row).toHaveClass(/group/)
  // GRP : bord gauche épais collé à la carte, élargie vers la gauche sans décaler le contenu.
  const other = page.locator('.sortable-row').filter({ hasText: 'Bernard L.' })
  const card = (await row.locator('.patient-row').boundingBox())!
  const otherCard = (await other.locator('.patient-row').boundingBox())!
  expect(card.x).toBeCloseTo(otherCard.x - 5, 0)
  expect(card.x).toBeGreaterThan(0)
  expect(await row.locator('.patient-row').evaluate(element => parseFloat(getComputedStyle(element).borderLeftWidth))).toBeGreaterThanOrEqual(5)
  const weeks = row.locator('.transmission .weeks')
  await expect(weeks).toHaveText('0')
  expect((await weeks.boundingBox())!.x).toBeLessThan((await row.locator('.transmission .triangle').boundingBox())!.x)
  // Un nombre à deux chiffres tient dans la carte sans décaler le nom.
  const nameX = async (target: typeof row) => (await target.locator('.patient-name').boundingBox())!.x
  const before = await nameX(row)
  expect(before).toBeCloseTo(await nameX(other), 0)
  await weeks.evaluate(element => { element.textContent = '12' })
  expect(await nameX(row)).toBeCloseTo(before, 0)
  expect((await weeks.boundingBox())!.x).toBeGreaterThan(card.x + 5)
  expect(((await weeks.boundingBox())!.x) - otherCard.x).toBeLessThan(10)
  await expect(page.locator('.sortable-row').filter({ hasText: 'Bernard L.' })).not.toHaveClass(/group/)

  await page.getByRole('link', { name: 'Patients' }).click()
  await page.getByRole('link', { name: /Bernard Louis/ }).click()
  await expect(page.getByRole('link', { name: '← Patients' })).toBeVisible()
})

test('copier le pointage du jour au format de l’export TXT', async ({ page }) => {
  await page.addInitScript(() => { Object.defineProperty(navigator, 'clipboard', { value: { writeText: async (text: string) => { (window as unknown as { copied: string }).copied = text } } }) })
  await page.goto('/#/?date=2026-09-28')
  const copy = page.locator('.day-summary').getByRole('button', { name: 'Copier' })
  await expect(copy).toBeDisabled()
  await page.getByRole('button', { name: 'A pour Martin Alice' }).click()
  await page.getByRole('button', { name: 'B pour Petit Jeanne' }).click()
  await page.getByRole('button', { name: 'H++', exact: true }).click()
  await page.getByLabel('Commentaire général').fill('calme')
  await expect(copy).toBeEnabled()
  await copy.click()
  await expect(page.locator('.day-summary').getByRole('button', { name: 'Copié ✓' })).toBeVisible()
  expect(await page.evaluate(() => (window as unknown as { copied: string }).copied)).toBe('28/09/2026\n++ calme\nMartin petit')
})

test('patient en attente d’une séance : interrupteur dans la fiche, « ! » rouge dans la fiche, la liste et la journée', async ({ page }) => {
  await page.goto('/#/patients')
  await page.getByRole('link', { name: /Martin Alice/ }).click()
  const toggle = page.getByRole('switch', { name: 'Attend une séance' })
  await expect(toggle).not.toBeChecked()
  await expect(page.locator('.waiting-mark')).toHaveCount(0)
  await toggle.click()
  await expect(toggle).toBeChecked()
  await expect(page.getByRole('heading', { level: 1 }).locator('.waiting-mark')).toHaveText('!')
  await page.reload()
  await expect(page.getByRole('switch', { name: 'Attend une séance' })).toBeChecked()
  await page.getByRole('link', { name: '← Patients' }).click()
  await expect(page.getByRole('link', { name: /Martin Alice \(attend une séance\)/ })).toBeVisible()
  await expect(page.locator('.patient-list .waiting-mark')).toHaveCount(1)
  await page.goto('/#/?date=2026-09-24')
  const row = page.locator('.sortable-row').filter({ hasText: 'Martin A.' })
  await expect(row.locator('.waiting-mark')).toHaveText('!')
  expect(await row.locator('.waiting-mark').evaluate(element => getComputedStyle(element).color)).toBe('rgb(196, 59, 51)')
  expect((await row.locator('.waiting-mark').boundingBox())!.x).toBeLessThan((await row.getByText('Martin A.').boundingBox())!.x + 1)
  await expect(page.locator('.tour-list .waiting-mark')).toHaveCount(1)
  await row.getByRole('link').click()
  await page.getByRole('switch', { name: 'Attend une séance' }).click()
  await page.getByRole('link', { name: '← jeudi 24 septembre' }).click()
  await expect(page.locator('.tour-list .waiting-mark')).toHaveCount(0)
})
